import os
import sys
import json
import time
import requests
from colorama import Fore

from aspm_cli.commands.base_command import BaseCommand
from aspm_cli.utils.logger import Logger
from aspm_cli.utils.common import poll_gate_status


class GateCommand(BaseCommand):
    help_text = "Poll the CI/CD quality gate and enforce pass/fail for this pipeline run."

    def configure_parser(self, parser):
        # Every value below is generated by the workflow (the same cli_id the scan
        # steps used) and handed in via flag or env. The gate just reads and uses them.
        parser.add_argument("--cli-id", dest="cli_id",
                            help="Pipeline run id (uuid) shared by all scanners. Falls back to "
                                 "ACCUKNOX_CLI_ID (the same value the scan steps used).")
        parser.add_argument("--scanner-prefixes", "--scanners", dest="scanner_prefixes",
                            help="Comma-separated artifact prefixes uploaded in this run "
                                 "(e.g. SG,SQ,FF,CX,TR,SO,SNYK,TruffleHog,IAC,SBOM) — the SAME values "
                                 "the scan steps uploaded. Falls back to ACCUKNOX_SCANNER_PREFIXES.")
        parser.add_argument("--endpoint", help="Control Panel URL. Falls back to ACCUKNOX_ENDPOINT.")
        parser.add_argument("--token", help="Auth token. Falls back to ACCUKNOX_TOKEN.")
        parser.add_argument("--tenant", help="Tenant ID [Optional]. Falls back to ACCUKNOX_TENANT. "
                                             "When set it is stamped on the poll; otherwise ignored.")
        parser.add_argument("--gate-timeout", dest="gate_timeout", type=int, default=300,
                            help="Max seconds to wait for evaluation to finish (default 300).")
        parser.add_argument("--gate-interval", dest="gate_interval", type=int, default=5,
                            help="Seconds between polls (default 5).")
        parser.add_argument("--gate-on-timeout", dest="gate_on_timeout", choices=["fail", "pass"], default="fail",
                            help="Action when results are not ready before timeout (default fail).")
        parser.add_argument("--softfail", action="store_true",
                            help="Report a gate breach but exit 0.")
        parser.set_defaults(func=self.execute)

    def execute(self, args):
        logger = Logger.get_logger()

        cli_id = (args.cli_id or os.getenv("ACCUKNOX_CLI_ID") or "").strip()
        endpoint = args.endpoint or os.getenv("ACCUKNOX_ENDPOINT")
        token = args.token or os.getenv("ACCUKNOX_TOKEN")
        tenant = (args.tenant or os.getenv("ACCUKNOX_TENANT") or "").strip() or None
        softfail = args.softfail or os.getenv("SOFT_FAIL") == "TRUE"
        # Prefixes are case-sensitive (e.g. TruffleHog) — trim only, never lowercase.
        raw_prefixes = args.scanner_prefixes or os.getenv("ACCUKNOX_SCANNER_PREFIXES") or ""
        prefixes = [s.strip() for s in raw_prefixes.split(",") if s.strip()]

        if not cli_id:
            logger.error(
                "cli-id is required: the workflow must generate one id before the scans "
                "and reuse it here (--cli-id or ACCUKNOX_CLI_ID)."
            )
            sys.exit(1)
        if not (endpoint and token):
            logger.error("endpoint and token are required (--endpoint/--token or ACCUKNOX_ENDPOINT/ACCUKNOX_TOKEN).")
            sys.exit(1)
        if not prefixes:
            # Without an explicit list the backend evaluates only the scanners that
            # finished so far, which can pass the gate prematurely while others are
            # still uploading. Make the risk loud.
            Logger.log_with_color(
                "WARNING",
                "No --scanner-prefixes given: the gate may evaluate only the scanners "
                "already recorded for this run and PASS before others finish. Pass the "
                "exact prefixes you uploaded (e.g. SG,TR,TruffleHog,SBOM).",
                Fore.YELLOW,
            )

        deadline = time.time() + args.gate_timeout
        data = None
        last_error = None
        while True:
            try:
                data = poll_gate_status(endpoint, token, cli_id, prefixes, tenant)
                last_error = None
            except requests.exceptions.HTTPError as e:
                status = getattr(getattr(e, "response", None), "status_code", None)
                if status in (401, 403):
                    # An un-authenticatable poll can never reach a verdict; fail closed
                    # immediately rather than burning the whole timeout window.
                    Logger.log_with_color(
                        "ERROR",
                        f"Gate poll authentication failed (HTTP {status}). Check the token "
                        "is a valid tenant-scoped token. Failing the build.",
                        Fore.RED,
                    )
                    sys.exit(1)
                if status == 404:
                    # Run not created yet (scanners still uploading / async eval). Keep
                    # waiting; the timeout is the backstop.
                    last_error = "no scan run for this cli_id yet (HTTP 404)"
                    logger.info(
                        f"No gate run found yet for cli_id={cli_id}; waiting for scanners to upload ..."
                    )
                else:
                    last_error = f"HTTP {status}" if status else str(e)
                    logger.warning(f"Gate poll failed (will retry): {last_error}")
                data = None
            except Exception as e:
                last_error = str(e)
                logger.warning(f"Gate poll failed (will retry): {e}")
                data = None

            if data and data.get("ready"):
                break

            if time.time() >= deadline:
                msg = f"Gate timed out after {args.gate_timeout}s waiting for evaluation."
                if last_error:
                    msg += f" Last poll issue: {last_error}."
                logger.warning(msg)
                # A timeout is an UN-EVALUATED gate (no verdict), not a known pass.
                # Honor --gate-on-timeout strictly; softfail only downgrades a real
                # breach verdict below, never an unknown-result timeout.
                if args.gate_on_timeout == "pass":
                    Logger.log_with_color("WARNING", "Gate timeout -> passing (--gate-on-timeout pass).", Fore.YELLOW)
                    sys.exit(0)
                Logger.log_with_color("ERROR", "Gate timeout -> failing the build (--gate-on-timeout fail).", Fore.RED)
                sys.exit(1)

            # Surface backend guidance (e.g. "pass scanner_prefix") when the run
            # exists but nothing is being evaluated.
            if data and not data.get("requested") and data.get("message"):
                Logger.log_with_color("WARNING", data["message"], Fore.YELLOW)
            pending = (data or {}).get("pending")
            if pending:
                logger.info(f"Waiting on scanners: {', '.join(pending)} ...")
            else:
                logger.info("Waiting for gate evaluation ...")
            time.sleep(args.gate_interval)

        self._render(data)

        # Build decision: a blocking verdict fails the build; softfail downgrades it.
        blocking = data.get("blocking", False)
        if blocking and softfail:
            Logger.log_with_color("WARNING", "Gate failed but softfail enabled; exiting 0.", Fore.YELLOW)
            sys.exit(0)
        sys.exit(1 if blocking else 0)

    def _render(self, data):
        status = data.get("status")
        color = Fore.RED if status in ("failed", "error") else (Fore.YELLOW if status == "warning" else Fore.GREEN)
        Logger.log_with_color(
            "INFO",
            f"CI/CD Gate: {status} (repo={data.get('repository')} branch={data.get('branch')})",
            color,
        )
        for prefix, res in (data.get("results") or {}).items():
            s = res.get("status")
            sc = Fore.RED if s in ("fail", "error") else (Fore.YELLOW if s == "warn" else Fore.GREEN)
            bucket = res.get("bucket")
            line = f"  [{prefix}]" + (f" ({bucket})" if bucket else "") + f" {s}"
            counts = res.get("counts") or {}
            if counts:
                line += f" counts={counts}"
            Logger.log_with_color("INFO", line, sc)
            for reason in res.get("reasons") or []:
                pol = reason.get("policy")
                detail = {k: v for k, v in reason.items() if k not in ("policy", "action")}
                Logger.log_with_color("INFO", f"      - policy '{pol}': {detail}", sc)
            if res.get("note"):
                Logger.log_with_color("INFO", f"      - note: {res['note']}", sc)
        # overall (combined-across-buckets) gate, when the policy declares one
        ov = data.get("overall")
        if ov:
            s = ov.get("status")
            sc = Fore.RED if s in ("fail", "error") else (Fore.YELLOW if s == "warn" else Fore.GREEN)
            line = f"  [overall] {s}"
            cc = ov.get("combined_counts") or {}
            if cc:
                line += f" combined={cc}"
            Logger.log_with_color("INFO", line, sc)
            for reason in ov.get("reasons") or []:
                pol = reason.get("policy")
                detail = {k: v for k, v in reason.items() if k not in ("policy", "action")}
                Logger.log_with_color("INFO", f"      - policy '{pol}': {detail}", sc)
        # machine-readable payload for downstream pipeline steps
        print(json.dumps(data, indent=2))
