name: Publish Docker Image

on:
  push:
    tags:
      - 'v*'
      
jobs:
  push_to_ecr:
    name: Build, Push Docker Image
    runs-on: ubuntu-latest
    env:
      RELEASE_TAG: ${{ github.ref_name }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_DEV_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEV_SECRET_ID }}
          aws-region: us-east-1

      - name: Login to AWS ECR
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.REPO }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.REPO }}:${{ env.RELEASE_TAG }} .

      - name: Push Docker image to ECR Public
        run: |
          docker push ${{ secrets.REPO }}:${{ env.RELEASE_TAG }}
